import os

DB_URL = os.getenv("DB_URL")
DB_NAME = os.getenv("DB_NAME")

BOT_TOKEN = os.getenv("BOT_TOKEN")
BOT_USERNAME = os.getenv("BOT_USERNAME")

PANEL_URL = os.getenv("PANEL_URL")
PANEL_TOKEN = os.getenv("PANEL_TOKEN")

ADMIN_ID = int(os.getenv("ADMIN_ID"))

USERNAME_PREFIX = os.getenv("USERNAME_PREFIX")

DEFAULT_TRAFFIC_LIMIT = int(os.getenv("DEFAULT_TRAFFIC_LIMIT"))
DEFAULT_TRAFFIC_STRATEGY = os.getenv("DEFAULT_TRAFFIC_STRATEGY")

SUBSCRIPTION_TRAFFIC_LIMIT = int(os.getenv("SUBSCRIPTION_TRAFFIC_LIMIT"))

DEFAULT_INBOUNDS = set(os.getenv("DEFAULT_INBOUNDS").split(","))

SUBS_DOMAIN = os.getenv("SUBS_DOMAIN")

WEBAPP_DOMAIN = os.getenv("WEBAPP_DOMAIN")
WEBAPP_PATH = os.getenv("WEBAPP_PATH")

WEBHOOK_PATH = os.getenv("WEBHOOK_PATH")

LOCAL_PORT = int(os.getenv("LOCAL_PORT"))

APP_URL = os.getenv("APP_URL")
SUPPORT_USERNAME = os.getenv("SUPPORT_USERNAME")

MESSAGES_CHANNEL = int(os.getenv("MESSAGES_CHANNEL"))
STICKER_ID = os.getenv("STICKER_ID")

START_MESSAGE_ID = int(os.getenv("START_MESSAGE_ID"))
MY_SUB_MESSAGE_ID = int(os.getenv("MY_SUB_MESSAGE_ID"))
BUY_SUB_MESSAGE_ID = int(os.getenv("BUY_SUB_MESSAGE_ID"))
BUY_MONTH_MESSAGE_ID = int(os.getenv("BUY_MONTH_MESSAGE_ID"))
BUY_YEAR_MESSAGE_ID = int(os.getenv("BUY_YEAR_MESSAGE_ID"))
CONFIRM_PAYMENT_MONTH_MESSAGE_ID = int(os.getenv("CONFIRM_PAYMENT_MONTH_MESSAGE_ID"))
CONFIRM_PAYMENT_YEAR_MESSAGE_ID = int(os.getenv("CONFIRM_PAYMENT_YEAR_MESSAGE_ID"))
REVOKE_PAYMENT_MESSAGE_ID = int(os.getenv("REVOKE_PAYMENT_MESSAGE_ID"))
EXPIRE_MESSAGE_ID = int(os.getenv("EXPIRE_MESSAGE_ID"))
LIMITED_MESSAGE_ID = int(os.getenv("LIMITED_MESSAGE_ID"))
